FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    git \
    python3.10 \
    python3-pip \
    python3-dev \
    python3-venv \
    build-essential \
    libpq-dev \
    vim \ 
    nano
COPY . /EosGround

CMD ["tail", "-f", "/dev/null"]