# Generated by Django 5.1.1 on 2024-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('num_satellites', models.IntegerField(blank=True, null=True)),
                ('flight_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_bytes', models.BinaryField()),
                ('rssi', models.IntegerField()),
                ('processed', models.BooleanField()),
                ('received_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'received_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReceivedPackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_type', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('generate_time', models.DateTimeField()),
                ('sequence_number', models.IntegerField()),
                ('send_time', models.DateTimeField()),
                ('received_time', models.DateTimeField()),
                ('packet_body', models.BinaryField()),
                ('processed', models.BooleanField()),
            ],
            options={
                'db_table': 'received_packets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('x_rotation', models.FloatField(blank=True, null=True)),
                ('y_rotation', models.FloatField(blank=True, null=True)),
                ('z_rotation', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
            ],
            options={
                'db_table': 'temperature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerminalOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_output', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'terminal_output',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_int', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransmitTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(blank=True, null=True)),
                ('packet_type', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('destination', models.IntegerField()),
                ('generate_time', models.DateTimeField()),
                ('body', models.BinaryField()),
            ],
            options={
                'db_table': 'transmit_table',
                'managed': False,
            },
        ),
    ]
