# Generated by Django 4.1.3 on 2022-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_type', models.TextField()),
                ('priority', models.TextField()),
                ('device', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
