# Generated by Django 4.1.3 on 2022-12-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_sent', models.DateTimeField(blank=True, default='')),
                ('packet_type', models.IntegerField(default=1)),
                ('packet_sender', models.IntegerField(default=1)),
                ('packet_priority', models.IntegerField(default=1)),
                ('packet_body', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
